// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanogramBackend.Data;

#nullable disable

namespace PlanogramBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714052755_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlanogramBackend.Models.ActualShelfSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("ComplianceScore")
                        .HasColumnType("float");

                    b.Property<string>("PhotoBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedImageUrls")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ActualShelfSubmissions");
                });

            modelBuilder.Entity("PlanogramBackend.Models.PlanogramGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlanogramGroups");
                });

            modelBuilder.Entity("PlanogramBackend.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlanogramGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanogramGroupId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("PlanogramBackend.Models.ProductImage", b =>
                {
                    b.HasOne("PlanogramBackend.Models.PlanogramGroup", "PlanogramGroup")
                        .WithMany("ProductImages")
                        .HasForeignKey("PlanogramGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanogramGroup");
                });

            modelBuilder.Entity("PlanogramBackend.Models.PlanogramGroup", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
